#-------------------------------
# General Site Settings

title: ISRD Dev Server
description: Development server for the Information Systems Research Division (ISRD) at ISI/USC.
email: cristina@isi.edu

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
#- {name: Home, url: 'index.html'}
- {name: GitHub, url: 'https://github.com/informatics-isi-edu'}
- {name: Slack, url: 'https://isi-isrd.slack.com/'}
- {name: Chaise Wiki, url: 'https://github.com/informatics-isi-edu/chaise/wiki'}
#- {name: Publications, url: '#pubs'}
#- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Add description'
  #rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  #rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  The Informatics Systems Research Division (ISRD) of ISI explores the intersection of healthcare
  and informatics. Launched in 2008, ISRD is applying Grid computing and other advanced information
  sciences concepts in an effort to transform the discovery processes, practice and delivery of
  healthcare worldwide.

